- contributor_iri: https://orcid.org/0000-0003-1144-0290
  contributor_literal: John Wieczorek
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: VertNet
  affiliation_uri: http://www.wikidata.org/entity/Q98382028

- contributor_iri: https://orcid.org/0000-0002-8442-8025
  contributor_literal: Peter Desmet
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
  affiliation_uri: http://www.wikidata.org/entity/Q7315097

- contributor_iri: https://orcid.org/0000-0003-4365-3135
  contributor_literal: Steve Baskauf
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Vanderbilt University Libraries
  affiliation_uri: http://www.wikidata.org/entity/Q16849893

- contributor_iri: https://orcid.org/0000-0001-6215-3617
  contributor_literal: Tim Robertson
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Global Biodiversity Information Facility
  affiliation_uri: http://www.wikidata.org/entity/Q1531570

- contributor_iri: https://orcid.org/0000-0001-7757-1889
  contributor_literal: Markus Döring
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Global Biodiversity Information Facility
  affiliation_uri: http://www.wikidata.org/entity/Q1531570

- contributor_iri: https://orcid.org/0000-0002-0596-5376
  contributor_literal: Quentin Groom
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Botanic Garden Meise
  affiliation_uri: http://www.wikidata.org/entity/Q3052500

- contributor_iri: https://orcid.org/0000-0001-6413-3185
  contributor_literal: Stijn Van Hoey
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
  affiliation_uri: http://www.wikidata.org/entity/Q7315097

- contributor_iri: https://orcid.org/0000-0003-1273-1807
  contributor_literal: David Bloom
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: VertNet
  affiliation_uri: http://www.wikidata.org/entity/Q98382028

- contributor_iri: https://orcid.org/0000-0002-6056-5084
  contributor_literal: Paula Zermoglio
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Instituto de Investigaciones en Recursos Naturales, Agroecología y Desarrollo Rural (IRNAD), UNRN-CONICET
  affiliation_uri: http://www.wikidata.org/entity/Q6156591

- contributor_iri: https://orcid.org/0000-0001-6682-1504
  contributor_literal: Robert Guralnick
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Florida, Florida Museum of Natural History
  affiliation_uri: http://www.wikidata.org/entity/Q501758

- contributor_iri: https://orcid.org/0000-0002-5905-1617
  contributor_literal: John Deck
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Genomic Biodiversity Working Group
  affiliation_uri: http://www.wikidata.org/entity/Q98382041

- contributor_iri: https://orcid.org/0000-0002-5178-4170
  contributor_literal: Gail Kampmeier
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Illinois Natural History Survey
  affiliation_uri: http://www.wikidata.org/entity/Q5999587

- contributor_iri: https://orcid.org/0000-0002-6513-4996
  contributor_literal: Dave Vieglais
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: KU Natural History Museum
  affiliation_uri: http://www.wikidata.org/entity/Q1111807

- contributor_iri: https://orcid.org/0000-0002-7104-7266
  contributor_literal: Renato De Giovanni
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Centro de Referência em Informação Ambiental
  affiliation_uri: http://www.wikidata.org/entity/Q29168927

- contributor_iri: https://orcid.org/0000-0003-1031-3249
  contributor_literal: Campbell Webb
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: TDWG RDF/OWL Task Group
  affiliation_uri: http://www.wikidata.org/entity/Q4914768

- contributor_iri: http://purl.oclc.org/net/edu.harvard.huh/guid/uuid/5e51de22-d841-4c47-b0c4-d5ad0bd03035
  contributor_literal: Paul J. Morris
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Harvard University Herbaria/Museum of Comparative Zoölogy
  affiliation_uri: http://www.wikidata.org/entity/Q51926077

- contributor_iri: https://orcid.org/0000-0003-0632-7576
  contributor_literal: Mark Schildhauer
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: National Center for Ecological Analysis and Synthesis
  affiliation_uri: http://www.wikidata.org/entity/Q6971323

- contributor_iri: https://orcid.org/0000-0001-9284-7900
  contributor_literal: Sophia Ratcliffe
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: National Biodiversity Network Trust
  affiliation_uri: http://www.wikidata.org/entity/Q6970988

- contributor_iri: https://orcid.org/0000-0002-1970-7044
  contributor_literal: Teresa J. Mayfield-Meyer
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: The University of New Mexico, Arctos
  affiliation_uri: http://www.wikidata.org/entity/Q1190812

- contributor_iri: https://orcid.org/0000-0002-6544-1363
  contributor_literal: Christian Bölling
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Museum für Naturkunde Berlin - Leibniz-Institut für Evolutions- und Biodiversitätsforschung
  affiliation_uri: http://www.wikidata.org/entity/Q233098

- contributor_iri: https://orcid.org/0000-0002-9284-8871
  contributor_literal: Laura Brenskelle
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Florida
  affiliation_uri: http://www.wikidata.org/entity/Q501758

- contributor_iri: https://orcid.org/0000-0002-4031-1968
  contributor_literal: Kitty Emery
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Florida
  affiliation_uri: http://www.wikidata.org/entity/Q501758

- contributor_iri: https://orcid.org/0000-0002-1741-9997
  contributor_literal: Michelle LeFebvre
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Florida
  affiliation_uri: http://www.wikidata.org/entity/Q501758

- contributor_iri: https://orcid.org/0000-0003-4740-286X
  contributor_literal: Neill Wallis
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Florida
  affiliation_uri: http://www.wikidata.org/entity/Q501758

- contributor_iri: https://orcid.org/0000-0002-8481-9034
  contributor_literal: Marie Elise Lecoq
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: GBIF France
  affiliation_uri: https://www.wikidata.org/wiki/Q1531570

- contributor_iri: https://orcid.org/0000-0001-5620-4764
  contributor_literal: Eric Kansa
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Harvard University
  affiliation_uri: http://www.wikidata.org/entity/Q13371

- contributor_iri: https://orcid.org/0000-0001-7920-5321
  contributor_literal: Sarah Kansa
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: The Alexandria Archive Institute
  affiliation_uri: https://www.wikidata.org/wiki/Q30257865

- contributor_iri: https://orcid.org/0000-0001-9325-3100
  contributor_literal: Denné Reed
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Texas at Austin
  affiliation_uri: https://www.wikidata.org/wiki/Q49213

- contributor_iri: https://orcid.org/0000-0002-1720-0127
  contributor_literal: Yanina V. Sica
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Yale University
  affiliation_uri: http://www.wikidata.org/entity/Q49112

- contributor_iri: https://orcid.org/0000-0001-5942-9053
  contributor_literal: Kate Ingenloff
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Global Biodiversity Information Facility (GBIF)
  affiliation_uri: http://www.wikidata.org/entity/Q1531570

- contributor_iri: https://orcid.org/0000-0001-7087-2646
  contributor_literal: Yi-Ming Gan
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Royal Belgian Institute of Natural Sciences
  affiliation_uri: http://www.wikidata.org/entity/Q16665660

- contributor_iri: https://orcid.org/0000-0001-9730-8340
  contributor_literal: Peter Brenton
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Atlas of Living Australia, CSIRO
  affiliation_uri: http://www.wikidata.org/entity/Q16335177

- contributor_iri: https://orcid.org/0000-0002-0595-7827
  contributor_literal: Wesley M. Hochachka
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Cornell Lab of Ornithology
  affiliation_uri: http://www.wikidata.org/entity/Q2997535

- contributor_iri: https://orcid.org/0000-0002-0500-0339
  contributor_literal: Zachary R. Kachian
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Keller Science Action Center, Field Museum of Natural History
  affiliation_uri: http://www.wikidata.org/entity/Q1122595

- contributor_iri: https://orcid.org/0000-0003-1617-5895
  contributor_literal: Robert D. Stevenson
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Department of Biology, University of Massachusetts Boston
  affiliation_uri: http://www.wikidata.org/entity/Q15144

- contributor_iri: https://orcid.org/0000-0003-2475-132X
  contributor_literal: Anahita J. N. Kazem
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: German Centre for Integrative Biodiversity Research, Leipzig and Friedrich Schiller University, Jena
  affiliation_uri: http://www.wikidata.org/entity/Q1206134

- contributor_iri: https://orcid.org/0000-0002-2919-1168
  contributor_literal: Dmitry Schigel
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Global Biodiversity Information Facility (GBIF)
  affiliation_uri: http://www.wikidata.org/entity/Q1531570

- contributor_iri: https://orcid.org/0000-0001-5010-3452
  contributor_literal: Tomomi Suwa
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Keller Science Action Center, Field Museum of Natural History
  affiliation_uri: http://www.wikidata.org/entity/Q1122595

- contributor_iri: https://orcid.org/0000-0001-8815-0078
  contributor_literal: Ramona L. Walls
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Arizona
  affiliation_uri: http://www.wikidata.org/entity/Q503419

- contributor_iri: https://orcid.org/0000-0002-1971-7277
  contributor_literal: Walter Jetz
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Yale University
  affiliation_uri: http://www.wikidata.org/entity/Q49112

- contributor_iri: https://orcid.org/0000-0002-6992-9446
  contributor_literal: Robert A. Morris
  contributor_role: lead author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: University of Massachusetts at Boston, USA
  affiliation_uri: http://www.wikidata.org/entity/Q15144

- contributor_iri: https://orcid.org/0000-0001-7023-7386
  contributor_literal: Gregor Hagedorn
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: JKI, Federal Research Institute for Cultivated Plants, Berlin, Germany
  affiliation_uri: http://www.wikidata.org/entity/Q832099

- contributor_iri: https://orcid.org/0000-0002-0772-0022
  contributor_literal: Annette Olson
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: American Association for the Advancement of Science
  affiliation_uri: http://www.wikidata.org/entity/Q40358

- contributor_iri: https://orcid.org/0000-0002-4852-2567
  contributor_literal: Vijay Barve
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: ''
  affiliation_uri: ''

- contributor_iri: https://orcid.org/0000-0002-8234-0599
  contributor_literal: Mihail Carausu
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Danish Biodiversity Information Facility (DanBIF), Copenhagen, Denmark
  affiliation_uri: http://www.wikidata.org/entity/Q1531570

- contributor_iri: https://orcid.org/0000-0002-3425-6499
  contributor_literal: Vishwas Chavan
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Global Biodiversity Information Facility, Copenhagen, Denmark
  affiliation_uri: http://www.wikidata.org/entity/Q1531570

- contributor_iri: http://www.wikidata.org/entity/Q51883873
  contributor_literal: José Cuadra
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: ''
  affiliation_uri: ''

- contributor_iri: https://orcid.org/0000-0002-2541-5822
  contributor_literal: Chris Freeland
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Missouri Botanical Garden, St. Louis, USA
  affiliation_uri: http://www.wikidata.org/entity/Q1852803

- contributor_iri: https://orcid.org/0000-0001-5172-8577
  contributor_literal: Patrick Leary
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: ''
  affiliation_uri: ''

- contributor_iri: https://orcid.org/0000-0003-1593-1417
  contributor_literal: Dimitry Mozzherin
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Encyclopedia of Life, Woods Hole, USA
  affiliation_uri: http://www.wikidata.org/entity/Q82486

- contributor_iri: https://orcid.org/0000-0002-3850-9983
  contributor_literal: Greg Riccardi
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Florida State University, Tallahassee, USA
  affiliation_uri: http://www.wikidata.org/entity/Q861548

- contributor_iri: https://orcid.org/0000-0003-4176-2274
  contributor_literal: Ivan Teage
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: ''
  affiliation_uri: ''

- contributor_iri: https://orcid.org/0000-0001-8068-3769
  contributor_literal: Dan Stowell
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Queen Mary University of London
  affiliation_uri: http://www.wikidata.org/entity/Q195668

- contributor_iri: https://orcid.org/0000-0002-5887-9543
  contributor_literal: Edward Baker
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Natural History Museum, London
  affiliation_uri: http://www.wikidata.org/entity/Q309388

- contributor_iri: https://orcid.org/0000-0003-0768-1286
  contributor_literal: Richard Pyle
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Bernice P. Bishop Museum, Honolulu, HI, USA
  affiliation_uri: http://www.wikidata.org/entity/Q826520
