date_issued: '2026-09-17'
local_offset_from_utc: +02:00
revision_directory: dwc-revisions
standard: http://www.tdwg.org/standards/450
decision_number: 62
decisions_text: Darwin Core changes ratified as a part of the Darwin Core public review. https://github.com/tdwg/dwc/milestone/22.
release_directory: dwc-revisions/dwc-revisions-2026-09-17
standard_label: Darwin Core
documents:
- document: http://rs.tdwg.org/dwc/doc/doe/
- document: http://rs.tdwg.org/dwc/doc/em/
- document: http://rs.tdwg.org/dwc/doc/pw/
- document: http://rs.tdwg.org/dwc/terms/guides/rdf/
- document: http://rs.tdwg.org/dwc/terms/guides/text/
- document: http://rs.tdwg.org/dwc/terms/guides/xml/
- document: http://rs.tdwg.org/dwc/terms/namespace/
- document: http://rs.tdwg.org/dwc/terms/simple/
- document: http://rs.tdwg.org/dwc/doc/hierarchy/
- document: http://rs.tdwg.org/dwc/doc/inclusive/
- document: http://rs.tdwg.org/dwc/doc/tcr/
- document: http://rs.tdwg.org/dwc/doc/cm/
- document: http://rs.tdwg.org/dwc/doc/dp/
- document: http://rs.tdwg.org/dwc/doc/list/
- document: http://rs.tdwg.org/dwc/doc/schemas/
vocabularies:
- vocab_type: 1
  list_of_terms_iri: http://rs.tdwg.org/dwc/doc/list/
  vocabulary: http://rs.tdwg.org/dwc/
  namespaces:
  - namespace_uri: http://rs.tdwg.org/dwc/terms/
    pref_namespace_prefix: dwc
    database: terms
    borrowed: false
    new_term_list: false
    utility_namespace: false
    termlist_uri: ''
    label: Core terms defined by Darwin Core
    description: This term list includes all currently valid terms that have been defined in the core Darwin Core namespace dwc:. To comment on this schema, please create a new issue in https://github.com/tdwg/dwc/issues.
    prepend_url: https://dwc.tdwg.org/list/#
    use_namespace_in_fragment: true
    separator: _
  - namespace_uri: http://rs.tdwg.org/dwc/iri/
    pref_namespace_prefix: dwciri
    database: iri
    borrowed: false
    new_term_list: false
    utility_namespace: false
    termlist_uri: ''
    label: Darwin Core IRI-value Term Analogs
    description: The terms on this list are intended to be used with IRI values.
    prepend_url: https://dwc.tdwg.org/list/#
    use_namespace_in_fragment: true
    separator: _
  - namespace_uri: http://rs.tdwg.org/eco/terms/
    pref_namespace_prefix: eco
    database: humboldt
    borrowed: false
    new_term_list: false
    utility_namespace: false
    termlist_uri: ''
    label: Humboldt Extension terms
    description: This list includes terms defined by the Humboldt Extension for Ecological Inventories.
    prepend_url: https://dwc.tdwg.org/list/#
    use_namespace_in_fragment: true
    separator: _
  - namespace_uri: http://rs.tdwg.org/eco/iri/
    pref_namespace_prefix: ecoiri
    database: humboldt_iri
    borrowed: false
    new_term_list: false
    utility_namespace: false
    termlist_uri: ''
    label: Humboldt Extension IRI terms
    description: This list includes terms defined by the Humboldt Extension for Ecological Inventories for use with IRI values.
    prepend_url: https://dwc.tdwg.org/list/#
    use_namespace_in_fragment: true
    separator: _
  - namespace_uri: http://rs.tdwg.org/chrono/terms/
    pref_namespace_prefix: chrono
    database: chronometricage
    borrowed: false
    new_term_list: false
    utility_namespace: false
    termlist_uri: ''
    label: Terms defined by the Chronometric Age Vocabulary
    description: This list includes terms defined by the Chronometric Age Vocabulary
    prepend_url: https://dwc.tdwg.org/list/#
    use_namespace_in_fragment: true
    separator: _
  - namespace_uri: http://rs.tdwg.org/chrono/iri/
    pref_namespace_prefix: chronoiri
    database: chronoiri
    borrowed: false
    new_term_list: false
    utility_namespace: false
    termlist_uri: ''
    label: Darwin Core chronometric age extension (IRI-values)
    description: Chronometric age extension (IRI values) for Darwin Core
    prepend_url: https://dwc.tdwg.org/list/#
    use_namespace_in_fragment: true
    separator: _
  - namespace_uri: http://rs.tdwg.org/ac/terms/
    pref_namespace_prefix: ac
    database: ac-for-dwc
    borrowed: true
    new_term_list: false
    utility_namespace: false
    termlist_uri: http://rs.tdwg.org/dwc/ac/
    label: Audiovisual Core terms used by Darwin Core
    description: This term list includes all terms that have been adopted from the Audiovisual Core namespace ac:.
    prepend_url: https://dwc.tdwg.org/list/#
    use_namespace_in_fragment: true
    separator: _
  - namespace_uri: http://purl.org/dc/elements/1.1/
    pref_namespace_prefix: dc
    database: dc-for-dwc
    borrowed: true
    new_term_list: false
    utility_namespace: false
    termlist_uri: http://rs.tdwg.org/dwc/dc/
    label: Darwin Core terms borrowed from the Dublin Core legacy namespace
    description: "This list includes terms borrowed by Darwin Core from the legacy (http://purl.org/dc/elements/1.1/) Dublin Core namespace "
    prepend_url: https://dwc.tdwg.org/list/#
    use_namespace_in_fragment: true
    separator: _
  - namespace_uri: http://purl.org/dc/terms/
    pref_namespace_prefix: dcterms
    database: dcterms-for-dwc
    borrowed: true
    new_term_list: false
    utility_namespace: false
    termlist_uri: http://rs.tdwg.org/dwc/dcterms/
    label: Darwin Core terms borrowed from the Dublin Core terms namespace
    description: "This list includes terms borrowed by Darwin Core from the terms (http://purl.org/dc/terms/) Dublin Core namespace "
    prepend_url: https://dwc.tdwg.org/list/#
    use_namespace_in_fragment: true
    separator: _
  vocabulary_label: Darwin Core main vocabulary
  vocabulary_description: This vocabulary contains Darwin Core and borrowed terms suitable for use with both literal and IRI values.
  dc_creator: TDWG Darwin Core Maintenance Group
  dcterms_license: https://creativecommons.org/licenses/by/4.0/
- vocabulary: http://rs.tdwg.org/dwcem/
  vocab_type: 2
  list_of_terms_iri: http://rs.tdwg.org/dwc/doc/em/
  vocabulary_label: Establishment Means Controlled Vocabulary
  vocabulary_description: A controlled vocabulary for the Darwin Core term dwc:establishmentMeans.
  dc_creator: TDWG Darwin Core Maintenance Group
  dcterms_license: https://creativecommons.org/licenses/by/4.0/
  namespaces:
  - namespace_uri: http://rs.tdwg.org/dwcem/values/
    pref_namespace_prefix: dwcem
    database: establishmentMeans
    borrowed: false
    new_term_list: false
    utility_namespace: false
    termlist_uri: ''
    use_namespace_in_fragment: true
    separator: _
    label: establishmentMeans controlled values list
    description: Controlled values list for the Darwin Core term establishmentMeans
    prepend_url: https://dwc.tdwg.org/em/#
- vocabulary: http://rs.tdwg.org/dwcdoe/
  vocab_type: 2
  list_of_terms_iri: http://rs.tdwg.org/dwc/doc/doe/
  vocabulary_label: degreeOfEstablishment controlled vocabulary
  vocabulary_description: Controlled vocabulary for the Darwin Core term degreeOfEstablishment
  dc_creator: TDWG Darwin Core Maintenance Group
  dcterms_license: http://creativecommons.org/licenses/by/4.0/
  namespaces:
  - namespace_uri: http://rs.tdwg.org/dwcdoe/values/
    pref_namespace_prefix: dwcdoe
    database: degreeOfEstablishment
    borrowed: false
    new_term_list: false
    utility_namespace: false
    termlist_uri: ''
    use_namespace_in_fragment: true
    separator: _
    label: degreeOfEstablishment controlled values list
    description: Controlled values list for the Darwin Core term degreeOfEstablishment
    prepend_url: https://dwc.tdwg.org/doe/#
- vocabulary: http://rs.tdwg.org/dwcpw/
  vocab_type: 3
  list_of_terms_iri: http://rs.tdwg.org/dwc/doc/pw/
  vocabulary_label: Pathway Controlled Vocabulary
  vocabulary_description: A controlled vocabulary for the Darwn Core term dwc:pathway.
  dc_creator: TDWG Darwin Core Maintenance Group
  dcterms_license: https://creativecommons.org/licenses/by/4.0/
  namespaces:
  - namespace_uri: http://rs.tdwg.org/dwcpw/values/
    pref_namespace_prefix: dwcpw
    database: pathway
    borrowed: false
    new_term_list: false
    utility_namespace: false
    termlist_uri: ''
    use_namespace_in_fragment: true
    separator: _
    label: pathway controlled values list
    description: Controlled values list for the Darwin Core term pathway
    prepend_url: https://dwc.tdwg.org/pw/#
- vocabulary: http://rs.tdwg.org/ecotcr/
  vocab_type: 2
  list_of_terms_iri: http://rs.tdwg.org/dwc/doc/tcr/
  vocabulary_label: Taxon Completeness Reported Controlled Vocabulary
  vocabulary_description: A controlled vocabulary for the term eco:taxonCompletenessReported.
  dc_creator: TDWG Humboldt Extension Task Group
  dcterms_license: https://creativecommons.org/licenses/by/4.0/
  namespaces:
  - namespace_uri: http://rs.tdwg.org/ecotcr/values/
    pref_namespace_prefix: ecotcr
    database: taxonCompletenessReported
    borrowed: false
    new_term_list: false
    utility_namespace: false
    termlist_uri: ''
    use_namespace_in_fragment: true
    separator: _
    label: taxonCompletenessReported controlled values list
    description: Controlled values list for the Humboldt Extension for Ecological Inventories term taxonCompletenessReported.
    prepend_url: https://eco.tdwg.org/tcr/#
standard_description: Darwin Core is a standard maintained by the Darwin Core maintenance group intended to facilitate the sharing of information about biological diversity. It includes a conceptual model, specifications for sharing biodiversity data using various formats (RDF, TXT, XML, Data Package), glossaries of terms, and data sharing schemas.
